-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 19:29:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `steemrocks`;
CREATE SCHEMA IF NOT EXISTS `steemrocks` DEFAULT CHARACTER SET utf8 ;
USE `steemrocks` ;

-- -----------------------------------------------------
-- Table `steemrocks`.`blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steemrocks`.`blocks` (
  `timestamp` DATETIME NULL,
  `witness` VARCHAR(64) NULL,
  `num` BIGINT(20) NOT NULL,
  `raw_data` JSON NULL,
  `id` VARCHAR(45) NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steemrocks`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steemrocks`.`transactions` (
  `id` VARCHAR(40) NOT NULL,
  `block_num` BIGINT(20) NULL,
  `raw_data` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `block_id_reference_idx` (`block_num` ASC),
  CONSTRAINT `block_id_reference`
    FOREIGN KEY (`block_num`)
    REFERENCES `steemrocks`.`blocks` (`num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steemrocks`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steemrocks`.`accounts` (
  `username` VARCHAR(45) NOT NULL,
  `last_account_update` DATETIME NULL,
  `raw_data` JSON NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `steemrocks`.`operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `steemrocks`.`operations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tx_id` VARCHAR(40) NOT NULL,
  `type` VARCHAR(64) NULL,
  `actor` VARCHAR(45) NULL,
  `effected` VARCHAR(45) NULL,
  `raw_data` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `actore_reference_idx` (`actor` ASC),
  INDEX `effected_reference_idx` (`effected` ASC),
  CONSTRAINT `tx_id_reference`
    FOREIGN KEY (`tx_id`)
    REFERENCES `steemrocks`.`transactions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE `steemrocks`.`operations`
ADD COLUMN `created_at` DATETIME NULL AFTER `raw_data`;


ALTER TABLE `steemrocks`.`operations`
DROP FOREIGN KEY `tx_id_reference`;



ALTER TABLE `operations` ADD UNIQUE `unique_index`(`tx_id`, `type`, `actor`, `effected`);
